# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88e3667d54ae1c34d4564fe16ad3ec7dc7be1ff4b4832e31b1772e8bea23d616b86473d4eb6a4f34497c6009a1790f5660bf241069c0e48e406a6f9084bf469c

test:
  secret_key_base: 670f30fe7387ebb53fa82b310928110e617d34766d596ccc64d44528714b994a9305b67046e503d033017a64b1275a8e5708eae012a731b01505fe6da1540b0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
